# wkd-proxy default config file
# this is in TOML format

keyserver="hkps://api.protonmail.ch"
logLevel="INFO"

## LogFile defaults to STDERR
#logFile=""
#hostname="localhost"

[http]
bind=":8080"
#logRequestDetails=false

## Uncomment this section to enable HTTPS
#[https]
#bind=":8443"
#cert="tls.cert"
#key="tls.key"
